export const MODAL_ACTIVE = "MODAL_ACTIVE";
export const MODAL_INACTIVE = "MODAL_INACTIVE";
export const START_FETCHING_CARDS = "START_FETCHING_CARDS";
export const SEARCH = "SEARCH";
export const ADD_POKEMON = "ADD_POKEMON";
export const REMOVE_POKEMON = "REMOVE_POKEMON";
